// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNLN4DiZXSOLE242Unw4xoSE6nGAAJ5fM',
    appId: '1:177318867182:web:a2aa0c728f92a576d8c3ff',
    messagingSenderId: '177318867182',
    projectId: 'trackit-e58f1',
    authDomain: 'trackit-e58f1.firebaseapp.com',
    storageBucket: 'trackit-e58f1.appspot.com',
    measurementId: 'G-DHF1K3G6ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwtmy6eW6ZoTpC4laQnrsHIbMEzEminM',
    appId: '1:177318867182:android:30a7c9b1e124917fd8c3ff',
    messagingSenderId: '177318867182',
    projectId: 'trackit-e58f1',
    storageBucket: 'trackit-e58f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIYOeBvCKs18mJLJ1R8RMxhdF0KDP7Sk',
    appId: '1:177318867182:ios:69d1692e0ff78329d8c3ff',
    messagingSenderId: '177318867182',
    projectId: 'trackit-e58f1',
    storageBucket: 'trackit-e58f1.appspot.com',
    iosBundleId: 'com.example.trackit',
  );
}
